### ISSUE TITLE
Can't execute pycorrfit

### ISSUE THREAD

**Issue by patta42** [paulmueller/PyCorrFit#101]
Hi there!

I'm trying to run pycorrfit on a SuSE13.1 machine. I have installed it using 

`> sudo pip install pycorrfit`

and the corresponding files are found in /usr/lib64/

However, when I try to start it or import it in ipython, I get an ImportError:

from .read_pt3_scripts.correlation_objects import picoObject

 ImportError: No module named read_pt3_scripts.correlation_objects

In the directory 'read_pt3_scripts' there are only two files named fib4.pyx and  fib4.so, but no file correlation_objects.py. I also have downloaded the source tgz, and there the content of the directory is the same.

Is this file missing, do I have to generate it somehow, or how can I get pycorrfit to run?

Regards,

Patrick

**Comment by patta42** [comment]
After I downloaded all the missing files from github and added a __init__.py in the directory, pycorrfit starts. So I assume the files are simply missing in the version installed using pip...

**Comment by paulmueller** [comment]
Hi Patrick,

that is very strange. I thought I just fixed this problem. The latest release on pypi also contains the files you mention. Did you try:

    sudo pip install https://pypi.python.org/packages/source/p/pycorrfit/pycorrfit-0.8.7-1.tar.gz#md5=bf4ea21fddac7e9c44122d8411128907

Thanks for reporting.

**Comment by patta42** [comment]
Hi Paul,

this worked now. I also uninstalled it again and used 

`> sudo pip install pycorrfit`

again, and this now works, too. My last try reported above was some days old, maybe the repository was not yet updated.

One minor remark: The title of the window now shows `PyCorrFit 0.0.0 - ...`.

**Comment by paulmueller** [comment]
I need your help concerning the wrong version of PyCorrFit. I assume that PyCorrFit was installed in 

    /usr/lib64/python2.7/dist-packages/pycorrfit/

Could you please verify that this file exists:

    /usr/lib64/python2.7/dist-packages/pycorrfit_doc/ChangeLog.txt

or was it installed somewhere else?
You could find out by typing

     sudo updatedb
     sudo locate ChangeLog.txt | grep pycorrfit

Thanks!

**Comment by patta42** [comment]
pycorrfit is installed in

`/usr/lib64/python2.7/site-packages/pycorrfit/` (not dist-packages)

However, the `pycorrfit_doc` directory and the ChangeLog are in  `/usr/lib/`

`> find /usr/lib* -name 'ChangeLog.txt'
/usr/lib/python2.7/site-packages/pycorrfit_doc/ChangeLog.txt`

HTH,

Patrick

**Comment by paulmueller** [comment]
Thanks,
this is what I get for reading the program version from the changelog file. In this rare case it did not work. I fixed it. The version should be displayed correctly in the next release.
Cheers
