### ISSUE TITLE
could not open ASC files of ALV7004 correlator 

### ISSUE THREAD

**Issue by fcsler** [paulmueller/PyCorrFit#104]
The following errror message appears when i try to open a ASC files generated by ALV7004 correlator:
"The following files could not be processed: <FILENAME>.ASC"

**Comment by paulmueller** [comment]
I might have fixed this problem in version 0.8.8. Could you please try if it works now?

**Comment by vschroeder** [comment]
Hi! 

Apperently the import does not work for all ALV7004 files. With the attached file I get the following error. That file contains only one run, maybe thats the problem. I use 0.8.8.

http://www.roentgen.physik.uni-goettingen.de/~vschroeder/dia10_cen10_0001.ASC

![error](https://cloud.githubusercontent.com/assets/6124136/8003036/2f7b8c6c-0b74-11e5-989a-d8911c6c3b0c.png)

**Comment by dmfractal** [comment]
Similar problem, program shut down when trying to open ALV-7004 *.asc file, system - WinXP 32-bit. No error message, just immediate shut down. The same problem with ALV-5000/E *.asc files.

**Comment by paulmueller** [comment]
@dmfractal 
Could you please upload two corresponding files somewhere? If you don't mind I would also like to include them in a future testing scheme.

**Comment by dmfractal** [comment]
Here you are,
ALV-5000/E: http://wikisend.com/download/120132/1.ASC
ALV-7004: http://wikisend.com/download/700798/2.ASC

**Comment by paulmueller** [comment]
Could you please check the latest release?

**Comment by vschroeder** [comment]
For my file (http://www.roentgen.physik.uni-goettingen.de/~vschroeder/dia10_cen10_0001.ASC) it is still the same error as above with 0.8.8-beta1

**Comment by paulmueller** [comment]
@vschroeder 
is this AC or CC data? fix is on the way...

**Comment by vschroeder** [comment]
that file is only one column of ac data although the 'mode' line says ac and cc. 
Here is a file with true A-CH0+1  C-CH0/1+1/0:
http://www.roentgen.physik.uni-goettingen.de/~vschroeder/ac01_cc01_10.ASC
Thanks a lot for your efforts!

**Comment by paulmueller** [comment]
It should work now.
If you have more ALV file that do not work, please create a new issue.

**Comment by vschroeder** [comment]
yes it works. thanks!
