### ISSUE TITLE
/usr/bin/pycorrfit, debian packaging

### ISSUE THREAD

**Issue by mestia** [paulmueller/PyCorrFit#105]
Hi Paul, 

I am tring to make the debian package of the new version of pycorrfit. It all works good, but when I run the /usr/bin/pycorrfit script it gives me the following output:
$pycorrfit 
Traceback (most recent call last):
  File "/usr/bin/pycorrfit", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pycorrfit==0.8.8

Any hint ? 

python -m pycorrfit works fine.

Thank you
Alex

**Comment by paulmueller** [comment]
It looks like pycorrfit is not installed correctly. System Python cannot find it.
If I run `sudo python setup.py install`, the `pycorrfit` script is installed to `/usr/local/bin/`.

Does `python -m pycorrfit` work outside of the cloned repository?

**Comment by mestia** [comment]
Yes, `python -m pycorrfit` works outside of the repository when the package is isntalled.

Another question, how the split between pycorrfit module and gui is done ? is it the same code, just called with different options ?

**Comment by paulmueller** [comment]
The `GUI` requirement only adds dependencies during installation. The code is exactly the same. You can install pycorrfit without `[GUI]`, install "wxPython", "matplotlib >= 1.1.0", "sympy >= 0.7.2" by hand, and there should not be any difference.

**Comment by paulmueller** [comment]
Is the correct version of PyCorrFit (0.8.8) displayed when you execute it with `python -m pycorrfit`?
Are you running on Debian Jessie?

**Comment by mestia** [comment]
it seems that I managed to solve the problem, the egg-info directory was missing in the package.
yes, I run Jessie.
