### ISSUE TITLE
ASCII error on Windows; statistics panel

### ISSUE THREAD

**Issue by paulmueller** [paulmueller/PyCorrFit#112]

**Comment by Ilanila** [comment]
Sir, I am a new user and am using windows 64 bit version .exe file downloaded installed. When I tried exporting the statistics data it showed an error as shown in the attached image. Should I install some other small file or is there any other way I could transfer the data.
P.S. The same error showed when I tried saving the plot as image.

![error](https://cloud.githubusercontent.com/assets/13236655/8569382/b1bcc968-2594-11e5-973e-ab3797eaf203.JPG)

**Comment by paulmueller** [comment]
Which fitting model were you using?
Does this also happen with the 32bit version?

**Comment by Ilanila** [comment]
The fitting model which I used was "Confocal (Gaussian) T+2D". I have not
installed 32 bit version since my pc is of 64 bit version. I was planning
to check by installing the 32 bit version.
​

**Comment by Ilanila** [comment]
Yes sir I checked with 32 bit version it is giving the same message.


- Ilanila.I.P
Ph.D student
IISC, Bangalore

- I.P.ILANILA

**Comment by paulmueller** [comment]
I might have fixed this issue in the next version (>0.8.8).
https://github.com/paulmueller/PyCorrFit/releases

**Comment by Ilanila** [comment]
I have actually installed that version only. Since I am a new user I
downloaded the latest version. I have not used any previous versions. Since
you gave me the link I tried re-installing again. Still the same message.
Thank you

- I.P.ILANILA
