### ISSUE TITLE
Exporting fits to csv - experimental correlation curve no longer matches up with fit curve

### ISSUE THREAD

**Issue by sarahumphreys** [paulmueller/PyCorrFit#120]
When I fit my FCS curve with the Confocal Gaussian T+3D+2D model, the fit looks good within PyCorrfit.  However, when I export the data from the current page as a .csv file and try to plot it in another program, I find that the fitted correlation curve no longer aligns with the experimental correlation curve.  I haven't tried doing this using other models.  Any ideas?

**Comment by paulmueller** [comment]
I cannot reproduce this. Could you please describe exactly what you were doing and maybe upload the .csv file somewhere or add a screenshot? Thanks.

**Comment by paulmueller** [comment]
I assume this is working in the latest release.
