### ISSUE TITLE
Average Data does not work

### ISSUE THREAD

**Issue by Recouvreux** [paulmueller/PyCorrFit#123]
Hi,
I downloaded the latest release for mac : PyCorrFit_0.8.8_macOSx_10.9.5.dmg and installed it on my mac (OSx10.10.5)
The software works fine, I can open fcs files, fit curves, save sessions. However when it comes to Average data tool I face an error which I paste below:

Traceback (most recent call last):
  File "/Users/travis/build/paulmueller/PyCorrFit/build/PyCorrFit_mac/out00-PYZ.pyz/pycorrfit.tools.average", line 137, in OnAverage
IndexError: PyCorrFit could not find the first page for averaging.

I open confocor3 .fcs files
My apologies if it is a simple error on my side. Thank you very much for this nice software!

Best,
Pierre Recouvreux

**Comment by paulmueller** [comment]
Thanks for reporting.
The pages that will be used for averaging can be selected in the dialog. By default, all pages are selected. However if pages are selected that do not exists, then this error might occur.

Try playing around with the "Create an average from the following pages" parameter.

If you think this error message is wrong or can be improved, please let me know.

**Comment by Recouvreux** [comment]
thanks for the quick answer. I forgot to mention but I already tried the "Create an average from the following pages" parameter: but it did not change the result. I also tried to uncheck the "Only use pages with the same model as the first page" option. 
Looking through some issues, I saw that an average with one page should work as well, but in my case it does not. 
I tried many combinations without any success...

**Comment by paulmueller** [comment]
I only get this error if I deliberately set wrong page numbers, e.g. if I set the pages to "0".
It is strange that you cannot create an average from one page.
Could you maybe attach a screenshot?

**Comment by Recouvreux** [comment]
below is a screenshot. When I set the page to "0" I get no message whatsoever when I click on "create average"
![capture d ecran 2015-08-20 a 14 06 54](https://cloud.githubusercontent.com/assets/13872909/9382921/0f0976f8-4745-11e5-9cbc-292336b375cf.png)

**Comment by paulmueller** [comment]
Thanks.
This bug has been fixed in a previous commit:

https://github.com/paulmueller/PyCorrFit/compare/new_fcs_classes#diff-9361a13643c84515573d4347336c7351L134

The corresponding branch will be merged soon. The next release should work.

**Comment by Recouvreux** [comment]
Ok, then I wait for the next release.

Thanks for your help.
Pierre

**Comment by paulmueller** [comment]
Next release is out. Please try again.

**Comment by Recouvreux** [comment]
Hi,
sorry for the late answer. I just tried the new release and the average works fine! 
Thanks a lot!
Pierre
