### ISSUE TITLE
Save Stat Error

### ISSUE THREAD

**Issue by naxir121** [paulmueller/PyCorrFit#131]
Dear Paul, 
When I try to save the statistic view, it always gives an error. Please see the image. Isn't there a way to save the stats as csv? Best...
![pycorrfit stat](https://cloud.githubusercontent.com/assets/6042119/10147484/22c969be-6626-11e5-801f-53837e946abb.png)

**Comment by paulmueller** [comment]
Thanks for reporting. This issue will be fixed in the next release. Please reopen if the problem persists.
