### ISSUE TITLE
Sessions saved with 64 bit Windows version won't open

### ISSUE THREAD

**Issue by joel-bentley** [paulmueller/PyCorrFit#136]
This is issue only with 64 bit Windows version (both 0.9.1 and 0.9.2).  Issue is not seen with 32 bit Windows version and Mac version. Computer is running Windows 7.

Error message is:
> ConstructorError: could not determine a constructor for the tag
> 'tag:yaml.org,2002:python/long'
> in "Parameters.yaml", line 125, column 9

Looking at Parameters.yaml in .pcfs file we see lines like this:
```yaml
  - [0, !!python/long '105']
```
In .pcfs files that we are able to open, these lines are instead
```yaml
  - [0, 105]
```
for example.

**Comment by paulmueller** [comment]
Thanks for reporting.
Note to myself:
Using `safe_dump` is the most likely solution.
http://stackoverflow.com/questions/1950306/pyyaml-dumping-without-tags

**Comment by paulmueller** [comment]
Unfortunately I don't have a x64bit Windows available. I might have solved this problem in the above commit. Could you please try this version:

https://ci.appveyor.com/api/buildjobs/m789i9n9na856b91/artifacts/Output/PyCorrFit_0.9.2_win_64bit_setup.exe

Thanks!

**Comment by joel-bentley** [comment]
Just tested new 64bit Windows version you provided above. No more errors! 
Session saved and reopened with no issues. 
Thanks!
