### ISSUE TITLE
Problem with the visualization of fit parameters

### ISSUE THREAD

**Issue by naxir121** [paulmueller/PyCorrFit#80]
Dear Paul,

I have been having a weird problem with the PyCorrFit. When I open the program, it does not show the parameters. Please see the attached image. I am using Win 8.1 (but it works on another computer using the same OS). 
Any comments would be helpful. Erdinc..
![screen shot pycorrfcs](https://cloud.githubusercontent.com/assets/6042119/3040014/c31bff24-e0e6-11e3-9db5-a40b6a8e2b2b.png)

**Comment by paulmueller** [comment]
I am closing this as it seems unlikely to reoccur.
