### ISSUE TITLE
MacOS app installation requires X11

### ISSUE THREAD

**Issue by weidemann** [paulmueller/PyCorrFit#82]
I use Mountain Lion 10.8.5. Download of the PyCorrFit.app (vs 0.8.3_alpha1) works but double clicking prompt the system to ask for the X11 developers kit, which is no longer part of MacOS. (http://support.apple.com/kb/HT5293).

As a temporary solution it would be nice to still get the binary for Mac.

**Comment by paulmueller** [comment]
This was probably an issue due to the former build machine. Please reopen if problem persists.
