### ISSUE TITLE
wxPython 3.0

### ISSUE THREAD

**Issue by mestia** [paulmueller/PyCorrFit#85]
Hi Paul, 

just for your information, pycorrfit and pyscanfcs in Debian were updated to use wxPython 3.0

https://anonscm.debian.org/cgit/debian-med/pycorrfit.git/plain/debian/patches/wx-migration-tools.patch

https://anonscm.debian.org/cgit/debian-med/pyscanfcs.git/tree/debian/patches/wx-migration-tools.patch

using this script
http://anonscm.debian.org/cgit/collab-maint/wx-migration-tools.git/tree/

Best regards, 
Alex

**Comment by paulmueller** [comment]
Migration to wxPython3
Pro:
- new entry_points will work with anaconda on Windows
- everyone else does it
Contra:
- wxPython3 is not in the repositories of current Ubuntu LTS and Debian stable

**Comment by mestia** [comment]
Debian testing is approaching the end of the freeze, and I believe the new stable will be soon released.
I think that release of Jessie (the next Debian stable) will also introduce wxPython3 in Ubuntu.
If only Debian and Ubuntu are concerned but other ways of distribution (pyinstaller,pip .. ) are not affected then I would suggest to go ahead and update.

**Comment by paulmueller** [comment]
I ran the script. The changes were harmless. 
PyCorrFit should run with both wxPython2.8.12 and wxPython3.
