### ISSUE TITLE
How to load the data with a new format *.data

### ISSUE THREAD

**Issue by jocelyn007** [paulmueller/PyCorrFit#87]
Dear Paul:
    I have the *.data file that were exported from a commercial software called "Shortcut to Sympho Time". When I load this file into the software, the result is not right. The format of my data looks like this:
Time[s]    Rate[count/ms]
0               8.9
0.01          29.3
0.02          38.4
............
599.989987	9.6

The change this file into "csv" format without words("time" or "rate"). I don't know what the data looks like in the  CSFCS_DiO-in-DOPC.pcfs because I cannot open it. 

What should I do some processing of this *.data file?

Best, 
Jocelyn

**Comment by paulmueller** [comment]
personal communication 2014-12-16
