### ISSUE TITLE
Unable to open .pt3 files (Mac and Windows)

### ISSUE THREAD

**Issue by phubert52** [paulmueller/PyCorrFit#89]
PyCorrFit 0.8.5 won't open .pt3 files (both in Mac OsX 10.8.6 and Windows 7).

![image](https://cloud.githubusercontent.com/assets/10419345/5720825/cae05694-9b29-11e4-93cf-b1593890e5fc.png)

Is there some pretreatment needed ?

Many thanks (again)
Pierre

**Comment by paulmueller** [comment]
Hi Pierre,
could you upload the file somewhere so I can have a look at what really happens?
Cheers,
Paul

**Comment by phubert52** [comment]
Hi Paul,
    
    here are two files, no password. First is Atto, second some protein
    in solution:
    
    
    https://bfs.imm.cnrs.fr/bfs/files/a3f05c53f4109afd3d01f3e17ef49b0d/ATTO488.pt3
    
    https://bfs.imm.cnrs.fr/bfs/files/14b35877e62570d20ec195ed89bd4d05/Point_4.pt3
    
    We are really looking forward to be using your software. Many many
    thanks
    
    Pierre
    
    Le 13/01/15 14:17, Paul Müller a
      écrit :
    
    
      Hi Pierre,
        could you upload the file somewhere so I can have a look at what
        really happens?
        Cheers,
        Paul
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      -----------------------------------------------
      Dr. Pierre Hubert, M.D., Ph.D. 
      LISM, CNRS-AMU UMR 7255, 31 Chemin Joseph Aiguier 
      13402 Marseille cedex20    France    
      tel. +33 (0)4 91 16 44 95    fax  +33 (0)4 91 71 21 24 
      http://www.researchgate.net/profile/Pierre_Hubert/

**Comment by phubert52** [comment]
Hi,
I checked the computers I used, the mac is 32 bits, the PC 64. Also I tried some sample files from PicoQuant, PyCorrFit 0.8.5 is able to open them on both machines. Such a file is here: 
https://bfs.imm.cnrs.fr/bfs/files/9c12b324e07b48ff6fae0b74efeeca91/Cy5_diff_IRF_FLCS_pattern.pt3
My own .pt3 files come from a LSM upgrade kit, could that make a difference ?

Best,
Pierre

**Comment by paulmueller** [comment]
The issue is fixed upstream, I will have to see how easy it is to make it work with PyCorrFit.

Cheers,
Paul

**Comment by phubert52** [comment]
Hi Paul,
    
    May I ask what is the current situation with pt3 files and PyCorrFit
    ?
    
    Many thanks,
    Best
    Pierre
    
    Le 14/01/15 17:03, Paul Müller a
      écrit :
    
    
      The issue is fixed upstream, I will have to see how easy it is
        to make it work with PyCorrFit.
      Cheers,
        Paul
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      -----------------------------------------------
      Dr. Pierre Hubert, M.D., Ph.D. 
      LISM, CNRS-AMU UMR 7255, 31 Chemin Joseph Aiguier 
      13402 Marseille cedex20    France    
      tel. +33 (0)4 91 16 44 95    fax  +33 (0)4 91 71 21 24 
      http://www.researchgate.net/profile/Pierre_Hubert/

**Comment by paulmueller** [comment]
Hi Pierre,

I still need to fuse the new script files from FCS_point_correlator with the PyCorrFit readfiles module. In principle, there is nothing in my way, except a lack of time. I hope this is not a big problem for you. I will get to it as soon as I am able to, but right now I am busy with a couple of other things. Keep in mind that I am doing this in my free time, i.e. I am not (yet) getting paid for developing PyCorrFit ;). 

Cheers,
Paul

**Comment by phubert52** [comment]
Hi Paul.
    
    Thanks for your answer. I certainly didn't mean to be pushy.
    
    We are eager to use your software (especially a PhD student in the
    lab) because we are having some problems with our current analysis
    (SymphoTime 32). I am a cell biologist, and anything that can make
    the use of equations more palatable is welcome.
    
    Please keep me informed of your progress.
    All the best.
    Pierre
    
    Le 26/01/15 19:44, Paul Müller a
      écrit :
    
    
      Hi Pierre,
      I still need to fuse the new script files from
        FCS_point_correlator with the PyCorrFit readfiles module. In
        principle, there is nothing in my way, except a lack of time. I
        hope this is not a big problem for you. I will get to it as soon
        as I am able to, but right now I am busy with a couple of other
        things. Keep in mind that I am doing this in my free time, i.e.
        I am not (yet) getting paid for developing PyCorrFit ;). 
      Cheers,
        Paul
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      -----------------------------------------------
      Dr. Pierre Hubert, M.D., Ph.D. 
      LISM, CNRS-AMU UMR 7255, 31 Chemin Joseph Aiguier 
      13402 Marseille cedex20    France    
      tel. +33 (0)4 91 16 44 95    fax  +33 (0)4 91 71 21 24 
      http://www.researchgate.net/profile/Pierre_Hubert/

**Comment by snizzleorg** [comment]
@phubert52 slightly off topic: what is the problem you are facing with the SymPhoTime32? - Maybe the PicoQuant Support (http://support.picoquant.com) can help?

**Comment by phubert52** [comment]
We want to analyse simultaneously several FCS curves, that's why we
    are interested in PyCorrFit.
    PH
    
    Le 27/01/15 17:29, snizzleorg a écrit :
    
    
      @phubert52 slightly off topic: what
        is the problem you are facing with the SymPhoTime32? - Maybe the
        PicoQuant Support (http://support.picoquant.com)
        can help? 
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      -----------------------------------------------
      Dr. Pierre Hubert, M.D., Ph.D. 
      LISM, CNRS-AMU UMR 7255, 31 Chemin Joseph Aiguier 
      13402 Marseille cedex20    France    
      tel. +33 (0)4 91 16 44 95    fax  +33 (0)4 91 71 21 24 
      http://www.researchgate.net/profile/Pierre_Hubert/

**Comment by snizzleorg** [comment]
SymPhoTime64 offers that. If you want I can ask for a Demo licence for you...

**Comment by phubert52** [comment]
Yes, thank you. 
    
    I know there is a version 2.0 of ST64, I have to contact the
    PicoQuant representative.
    
    
    Le 27/01/15 17:43, snizzleorg a écrit :
    
    
      SymPhoTime64 offers that. If you want I can ask for a Demo
        licence for you...
      —
        Reply to this email directly or view
          it on GitHub.
      
        
          
          
        
        
      
    
    
    -- 
      
      
      -----------------------------------------------
      Dr. Pierre Hubert, M.D., Ph.D. 
      LISM, CNRS-AMU UMR 7255, 31 Chemin Joseph Aiguier 
      13402 Marseille cedex20    France    
      tel. +33 (0)4 91 16 44 95    fax  +33 (0)4 91 71 21 24 
      http://www.researchgate.net/profile/Pierre_Hubert/

**Comment by paulmueller** [comment]
Hello,
I uploaded a new release 0.8.5-pt3dev1. 
https://github.com/paulmueller/PyCorrFit/releases
Could you please check if this version can open your files correctly?
Unfortunately, the links you supplied are not valid anymore. If you have no objections, I would like to upload them to GitHub as example files. Could you re-upload the pt3-files (optionally with some background information for the wiki)?
Cheers,
Paul

**Comment by phubert52** [comment]
Hi Paul,

many thanks for the info and your work.

I will not be in the lab until next Tuesday, but I'll try the new 
version as soon as possible. And of course I'll send again some pt3 
files with details. Our file server does not allow for long term file 
storage.

Best
Pierre

On 29/01/15 22:20, Paul Müller wrote:
>
> Hello,
> I uploaded a new release 0.8.5-pt3dev1.
> https://github.com/paulmueller/PyCorrFit/releases
> Could you please check if this version can open your files correctly?
> Unfortunately, the links you supplied are not valid anymore. If you 
> have no objections, I would like to upload them to GitHub as example 
> files. Could you re-upload the pt3-files (optionally with some 
> background information for the wiki)?
> Cheers,
> Paul
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/paulmueller/PyCorrFit/issues/89#issuecomment-72106395>.
>

-- 
Dr. Pierre Hubert, M.D., Ph.D.
LISM, CNRS UPR 9027	31 Chemin Joseph Aiguier
13402 Marseille cedex20	France	
http://lism.cnrs-mrs.fr/JS_files/Page_JS
tel. +33 (0)4 91 16 44 95
fax  +33 (0)4 91 71 21 24

**Comment by phubert52** [comment]
Hi Paul,
    
    Sorry it took me some time to come back to you.
    
    And many thanks for your work. PyCorrFit opens now our .pt3 files
    without problem.
    
    I am putting a zip containing 6 such files in our file server :
    https://bfs.imm.cnrs.fr/bfs/files/e30fd2bd3b08f7f158094e3d91932fe1/A42F_4jul2014.zip
    ;
    no password, files will be there for 7 days
    
    Data are single channel acquisitions of a monomeric membrane protein
    (~ 30kDa) in detergent (DDM) solution, labeled with atto 488.
    Equipment was a PicoQuant LSM upgrade on an Olympus FV1000
    microscope, with SymphoTime32; PQ pulsed laser 470 nm, 60x oil
    objective, PQ SPAD detector. Is that sufficient info ?
    
    Would mind mentioning the name of Ms. Victoria Schmidt, PhD student,
    who prepared the protein and ran the FCS with me ?
    
    Many thanks again, I'll keep you informed of our progresses with
    your software.
    
    Best
    Pierre
    
    Le 29/01/15 22:20, Paul Müller a
      écrit :
    
    
      Hello,
        I uploaded a new release 0.8.5-pt3dev1. 
        https://github.com/paulmueller/PyCorrFit/releases
        Could you please check if this version can open your files
        correctly?
        Unfortunately, the links you supplied are not valid anymore. If
        you have no objections, I would like to upload them to GitHub as
        example files. Could you re-upload the pt3-files (optionally
        with some background information for the wiki)?
        Cheers,
        Paul
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by paulmueller** [comment]
Great!

for your reference, I added an [Examples](https://github.com/paulmueller/PyCorrFit/wiki/Examples) section to the wiki. You should be able to change it if you want to add anything.

Best,
Paul

**Comment by paulmueller** [comment]
Hi David, unfortunately, I do not know where this error comes from. But if anyone would write a pull request that manages to fix this issue, I would be happy to merge it.

**Comment by djpeeler** [comment]
Hi Paul, thank you for your response. I should add that these .pt3 files are from a Leica SP8 system--perhaps someone knows if these files are exported differently or if there is other software available to analyze them? Much appreciated!
