### ISSUE TITLE
Import of ALV700X files 

### ISSUE THREAD

**Issue by vschroeder** [paulmueller/PyCorrFit#92]
Hi!

Would be possible to support ALV700X file? How different is it to the the other ALV files? The import doesn't work at the moment.

This is a file from a ALV7004:
http://www.roentgen.physik.uni-goettingen.de/~vschroeder/scan4.asc

Best, Viktor

**Comment by paulmueller** [comment]
Yes, the format does not seem to be much different.
May I use your file in the example section of the wiki?

**Comment by vschroeder** [comment]
Sure, you can use it.

**Comment by paulmueller** [comment]
I implemented experimental support for the ALV700X file you sent me. Could you try with the current master branch? If you need a compiled binary, you will have to wait until next week.

**Comment by vschroeder** [comment]
I tested the import and it works! Thanks a lot!

**Comment by vschroeder** [comment]
Hi! 

I'm opening this again because apperently the import does not work for all ALV7004 files. With the attached file I get the following error. That file contains only one run, maybe thats the problem.

http://www.roentgen.physik.uni-goettingen.de/~vschroeder/dia10_cen10_0001.ASC

![error](https://cloud.githubusercontent.com/assets/6124136/8003036/2f7b8c6c-0b74-11e5-989a-d8911c6c3b0c.png)
